/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-img-element */
"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, GripVertical, ImagePlus, Loader2, Trash2 } from "lucide-react";

const steps=["Organization","Basics","Location","Capacity","Amenities","Photos","Pricing","Profile","Review"];
type Draft={organizationId:string;organizationName:string;name:string;category:string;address:string;neighborhood:string;city:string;lat:string;lng:string;guests:string;bedrooms:string;beds:string;baths:string;amenities:string;policies:string;images:string[];price:string;quantity:string;minStay:string;template:string;description:string};
const empty:Draft={organizationId:"",organizationName:"",name:"",category:"residence",address:"",neighborhood:"",city:"Kigali",lat:"",lng:"",guests:"2",bedrooms:"1",beds:"1",baths:"1",amenities:"WiFi, Equipped kitchen, On-site parking",policies:"Check-in from 15:00. Check-out by 11:00.",images:[],price:"85000",quantity:"1",minStay:"1",template:"classic",description:""};
export function ListingWizard({existingOrganizationId=""}:{existingOrganizationId?:string}){const router=useRouter();const[step,setStep]=useState(existingOrganizationId?1:0);const[draft,setDraft]=useState<Draft>({...empty,organizationId:existingOrganizationId});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const drag=useRef<number|null>(null);
useEffect(()=>{const saved=localStorage.getItem("stayrwanda-listing-draft");if(saved)try{setDraft((current)=>({...current,...JSON.parse(saved),organizationId:existingOrganizationId||JSON.parse(saved).organizationId}))}catch{}},[existingOrganizationId]);
useEffect(()=>{localStorage.setItem("stayrwanda-listing-draft",JSON.stringify(draft))},[draft]);
const set=(key:keyof Draft,value:string|string[])=>setDraft((old)=>({...old,[key]:value}));
async function ensureOrganization(){if(draft.organizationId)return draft.organizationId;const slug=draft.organizationName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");const res=await fetch("/api/organizations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:draft.organizationName,slug})});const data=await res.json();if(!res.ok){setError(data.error);return ""}set("organizationId",data.organizationId);return String(data.organizationId)}
async function upload(files:FileList|null){if(!files?.length)return;const organizationId=await ensureOrganization();if(!organizationId)return;setBusy(true);for(const file of Array.from(files)){const body=new FormData();body.append("organizationId",organizationId);body.append("file",file);const res=await fetch("/api/upload",{method:"POST",body});const data=await res.json();if(res.ok)setDraft((old)=>({...old,images:[...old.images,data.url]}));else setError(data.error)}setBusy(false)}
function reorder(from:number,to:number){setDraft((old)=>{const images=[...old.images];const[item]=images.splice(from,1);images.splice(to,0,item);return{...old,images}})}
async function next(){setError("");if(step===0&&!await ensureOrganization())return;if(step===1&&draft.name.length<3)return setError("Add a property name.");if(step===2&&!draft.neighborhood)return setError("Add a neighbourhood.");if(step===5&&!draft.images.length)return setError("Upload at least one property photo.");if(step===7&&draft.description.length<40)return setError("Add a description of at least 40 characters.");setStep((value)=>Math.min(8,value+1))}
async function submit(){setBusy(true);setError("");const res=await fetch("/api/properties",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:draft.organizationId,title:draft.name,location:`${draft.city}, Rwanda`,address:draft.address,lat:draft.lat?Number(draft.lat):undefined,lng:draft.lng?Number(draft.lng):undefined,neighborhood:draft.neighborhood,type:draft.category,description:draft.description,price:Number(draft.price),quantity:Number(draft.quantity),minStay:Number(draft.minStay),template:draft.template,guests:Number(draft.guests),bedrooms:Number(draft.bedrooms),beds:Number(draft.beds),baths:Number(draft.baths),images:draft.images,amenities:draft.amenities.split(",").map(x=>x.trim()).filter(Boolean),host:draft.organizationName||"StayRwanda Partner"})});const data=await res.json();if(!res.ok){setError(data.error);setBusy(false);return}localStorage.removeItem("stayrwanda-listing-draft");router.push("/host/hotels");router.refresh()}
return <div className="mx-auto max-w-6xl"><div className="mb-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--gold-deep)]">New hospitality profile</p><h1 className="mt-2 font-serif text-4xl font-semibold text-[var(--ink)]">List your property</h1><p className="mt-2 text-sm text-[var(--muted)]">Draft changes save automatically on this device.</p></div><div className="grid gap-7 lg:grid-cols-[220px_1fr]"><ol className="h-fit border border-[#dedbd2] bg-white p-3">{steps.map((label,index)=><li key={label} className={`flex items-center gap-3 px-3 py-2.5 text-sm ${index===step?"bg-[var(--cream)] font-semibold text-[var(--ink)]":index<step?"text-[#287b45]":"text-[var(--muted)]"}`}><span className={`grid size-6 place-items-center rounded-full text-xs ${index<=step?"bg-[var(--gold)] text-white":"bg-[#eee]"}`}>{index<step?<Check size={13}/>:index+1}</span>{label}</li>)}</ol><section className="border border-[#dedbd2] bg-white p-6 sm:p-8"><h2 className="font-serif text-3xl font-semibold text-[var(--ink)]">{steps[step]}</h2><div className="mt-6 space-y-4">
{step===0&&<Field label="Organization or hotel group name" value={draft.organizationName} onChange={v=>set("organizationName",v)}/>}
{step===1&&<><Field label="Property name" value={draft.name} onChange={v=>set("name",v)}/><Select label="Property category" value={draft.category} onChange={v=>set("category",v)} options={[["residence","Residence"],["hotel","Hotel"],["guesthouse","Guesthouse"]]}/></>}
{step===2&&<><Field label="Street address" value={draft.address} onChange={v=>set("address",v)}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Neighbourhood" value={draft.neighborhood} onChange={v=>set("neighborhood",v)}/><Field label="City" value={draft.city} onChange={v=>set("city",v)}/><Field label="Latitude (optional)" value={draft.lat} onChange={v=>set("lat",v)} type="number"/><Field label="Longitude (optional)" value={draft.lng} onChange={v=>set("lng",v)} type="number"/></div></>}
{step===3&&<div className="grid grid-cols-2 gap-4 sm:grid-cols-4"><Field label="Guests" value={draft.guests} onChange={v=>set("guests",v)} type="number"/><Field label="Bedrooms" value={draft.bedrooms} onChange={v=>set("bedrooms",v)} type="number"/><Field label="Beds" value={draft.beds} onChange={v=>set("beds",v)} type="number"/><Field label="Bathrooms" value={draft.baths} onChange={v=>set("baths",v)} type="number"/></div>}
{step===4&&<><Area label="Amenities (comma separated)" value={draft.amenities} onChange={v=>set("amenities",v)}/><Area label="Policies" value={draft.policies} onChange={v=>set("policies",v)}/></>}
{step===5&&<><label className="flex cursor-pointer flex-col items-center border-2 border-dashed border-[#ccc] bg-[var(--cream)] p-10 text-sm text-[var(--muted)]">{busy?<Loader2 className="animate-spin"/>:<ImagePlus/>}<span className="mt-2">Upload JPG, PNG or WebP images</span><input type="file" multiple accept="image/*" className="hidden" onChange={e=>upload(e.target.files)}/></label><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{draft.images.map((image,index)=><div key={image} draggable onDragStart={()=>drag.current=index} onDragOver={e=>e.preventDefault()} onDrop={()=>drag.current!==null&&reorder(drag.current,index)} className="relative aspect-square overflow-hidden bg-[#eee]"><img src={image} alt="" className="h-full w-full object-cover"/><GripVertical className="absolute left-1 top-1 bg-white/80"/><button onClick={()=>set("images",draft.images.filter(x=>x!==image))} className="absolute right-1 top-1 bg-white/90 p-1 text-red-700"><Trash2 size={15}/></button>{index===0&&<span className="absolute bottom-1 left-1 bg-[var(--ink)] px-2 py-1 text-[9px] uppercase text-white">Cover</span>}</div>)}</div></>}
{step===6&&<div className="grid gap-4 sm:grid-cols-3"><Field label="Nightly rate (RWF)" value={draft.price} onChange={v=>set("price",v)} type="number"/><Field label="Available units" value={draft.quantity} onChange={v=>set("quantity",v)} type="number"/><Field label="Minimum stay" value={draft.minStay} onChange={v=>set("minStay",v)} type="number"/></div>}
{step===7&&<><Select label="Profile template" value={draft.template} onChange={v=>set("template",v)} options={[["classic","Classic Hospitality"],["editorial","Editorial Residence"],["modern","Modern Urban"]]}/><Area label="Property story" value={draft.description} onChange={v=>set("description",v)}/></>}
{step===8&&<div className="grid gap-5 sm:grid-cols-2"><Summary label="Organization" value={draft.organizationName||"Current organization"}/><Summary label="Property" value={`${draft.name} · ${draft.category}`}/><Summary label="Location" value={`${draft.neighborhood}, ${draft.city}`}/><Summary label="Capacity" value={`${draft.guests} guests · ${draft.bedrooms} bedrooms`}/><Summary label="Inventory" value={`${draft.quantity} units · RWF ${Number(draft.price).toLocaleString()}/night`}/><Summary label="Media" value={`${draft.images.length} photographs · ${draft.template} template`}/></div>}
</div>{error&&<p className="mt-5 bg-[#fbefed] p-3 text-sm text-[#a33]">{error}</p>}<div className="mt-8 flex justify-between border-t border-[#eee] pt-5"><button disabled={step===0} onClick={()=>setStep(v=>Math.max(0,v-1))} className="flex items-center gap-2 px-4 py-3 text-sm font-semibold disabled:opacity-30"><ArrowLeft size={17}/>Back</button>{step<8?<button onClick={next} className="flex items-center gap-2 bg-[var(--ink)] px-6 py-3 text-sm font-semibold text-white">Continue<ArrowRight size={17}/></button>:<button disabled={busy} onClick={submit} className="flex items-center gap-2 bg-[var(--gold)] px-6 py-3 text-sm font-semibold text-white">{busy&&<Loader2 size={16} className="animate-spin"/>}Submit for review</button>}</div></section></div></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-sm font-semibold text-[var(--ink)]">{label}<input type={type} value={value} min={type==="number"?0:undefined} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full border border-[#bbb] px-3 font-normal outline-none focus:border-[var(--gold)]"/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-semibold">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-28 w-full border border-[#bbb] p-3 font-normal outline-none focus:border-[var(--gold)]"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label className="block text-sm font-semibold">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full border border-[#bbb] bg-white px-3 font-normal">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Summary({label,value}:{label:string;value:string}){return <div className="border border-[#e2dfd6] bg-[var(--cream)] p-4"><span className="text-[10px] uppercase tracking-wider text-[var(--muted)]">{label}</span><strong className="mt-2 block text-[var(--ink)]">{value}</strong></div>}
